name: Test Dev (e2e)

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  # test:
  #   strategy:
  #     matrix:
  #       target: ["laurentsenta/bifrost-gateway"]
  #     fail-fast: false
  #   uses: ${{ matrix.target }}/.github/workflows/gateway-conformance.yml@main
  #   with:
  #     version_gway: "latest"
  #     artifact_json_name: ${{ matrix.target }}-output.json
  bifrost-gateway:
    uses: singulargarden/bifrost-gateway/.github/workflows/gateway-conformance.yml@main
    with:
      version_gway: "latest"
      artifact_json_name: conformance-bifrost-gateway.json
  aggregate:
    runs-on: "ubuntu-latest"
    needs: [bifrost-gateway]
    # the tests might have failed
    if: always()
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          path: "gateway-conformance"
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Aggregate results
        working-directory: ./artifacts
        run: |
          set -e
          set -o pipefail
          mkdir ./aggregates

          # download-artifact downloads artifacts in a directory named after the artifact
          # details: https://github.com/actions/download-artifact#download-all-artifacts
          for folder in ./conformance-*.json; do
            file="${folder}/output.json"
            new_file="aggregates/${folder#conformance-}"
            jq -ns 'inputs' "$file" | node ../gateway-conformance/aggregate.js 1 > "${new_file}"
          done

          node ../gateway-conformance/aggregate-into-table.js ./aggregates/*.json > ./table.md
      - name: Set summary
        if: (failure() || success())
        run: cat ./artifacts/table.md >> $GITHUB_STEP_SUMMARY