name: Test Dev (e2e)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  bifrost-gateway:
    uses: singulargarden/bifrost-gateway2/.github/workflows/gateway-conformance.yml@main
    with:
      artifact_json_name: conformance-bifrost-gateway.json
