# based on https://github.com/libp2p/test-plans/pull/86
name: Update Badge

on:
  workflow_run:
    workflows:
      - Test Production (e2e)
    types:
      - completed
      - completed-with-failure
    branches:
      - main
      - feat/text-production-gateways # temporary

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: pl-strflt/job-summary-url-action@v1
        name: get-metadata
        with:
          workflow: test-prod-e2e.yml # ${{ github.event.workflow.path }}
          run_id: ${{ github.event.workflow_run.id }}
          run_attempt: ${{ github.event.workflow_run.run_attempt }}
          job: aggregate
      - uses: actions/checkout@v3
      # https://github.com/orgs/community/discussions/26560
      - run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - run: |
          GITHUB_JOB_SUMMARY_URL="${{ steps.get-metadata.outputs.job_summary_url }}"

          IN='[![Conformance Production Dashboard](https://github.com/ipfs/gateway-conformance/actions/workflows/test-prod-e2e.yml/badge.svg?branch=master)](.*)'
          ESCAPED_IN=$(printf '%s\n' "$IN" | sed -e 's/[][\/!&]/\\&/g')

          OUT="[![Conformance Production Dashboard](https://github.com/ipfs/gateway-conformance/actions/workflows/test-prod-e2e.yml/badge.svg?branch=master)](${GITHUB_JOB_SUMMARY_URL})"

          sed -i "s;${ESCAPED_IN};${OUT};" README.md
      - run: |
          if [[ -n $(git diff --shortstat 2> /dev/null | tail -n1) ]]; then
            echo "GIT_DIRTY=1" >> $GITHUB_ENV
          else
            echo "GIT_DIRTY=0" >> $GITHUB_ENV
          fi
      - if: env.GIT_DIRTY == '1'
        run: |
          git add README.md
          git commit -m 'chore: update the link to the dashboard [skip ci]'
          git push
